### ISSUE TITLE
Which IDE you are using to Create and Edit pbdb.jet file?

### ISSUE THREAD

**Issue by guttevikas7** [arashpayan/Prayer-Book-Android#33]
Which IDE you are using to Create and Edit pbdb.jet file? Could you please help me, by providing more detail about it? That will be very helpful for us. Thank you in advance.!

**Comment by arashpayan** [comment]
I'm using the [pbdbbuider](https://github.com/arashpayan/pbdbbuilder) to create the database, along with [bpnet-scraper](https://github.com/arashpayan/bpnet-scraper) to merge the individual language databases, and add a searchable index to the final database for inclusion in the app.

@guttevikas7, are you interested in adding another language to the app?

**Comment by guttevikas7** [comment]
**@guttevikas7, are you interested in adding another language to the app?**
Ans:- Yes, I am looking to add more languages in app Specially Marathi and Hindi. And I want to know as well as want to learn how to create DB file. Is there any other way to create DB file? I have windows system and seems like your project the [pbdbbuider](https://github.com/arashpayan/pbdbbuilder) is in  CodeX. I don't have much idea about XCode. Is there any other way to create DB file? From Windows system. 

Thank you so much for quick reply.

**Comment by arashpayan** [comment]
The database is just an SQLite database, so if you want to write a Windows version of pbdbbuilder that would work.

However, that's a lot of work for just 2 languages. The quickest way to add Hindi and Marathi prayers to the app would be if you could assist me with translating the UI via transifex, and then spending 1-2 hours with me on a video chat to review some of the formatting issues I will inevitably encounter.

What do you think?

**Comment by guttevikas7** [comment]
That would be really good idea! But how i can add my won content in app? Because every time I can't ask you to do my work and I do not want to bother you again and again. I was thinking to add data for three languages along with translation in database (English, Hindi & Marathi) and show the data as per user selection. 
For Example - Will add below content in DB and present as per user selection
- What is your name? (If English selected)
- तुझं नाव काय आहे? (If Marathi selected)
- तुम्हारा नाम क्या हे? (If Hindi selected)
This might be silly idea 😉. So again my question is, how i can edit DB file, so i can add my own content?

Thank you so much for your time and comment.

**Comment by guttevikas7** [comment]
That would be really good idea! But how i can add my own content in app? Because every time I can't ask you to do my work and I do not want to bother you again and again. I was thinking to add data for three languages along with translation in database (English, Hindi & Marathi) and show the data as per user selection.
For Example - Will add below content in DB and present as per user selection

* What is your name? (If English selected)
* तुझं नाव काय आहे? (If Marathi selected)
* तुम्हारा नाम क्या हे? (If Hindi selected)
  This might be silly idea 😉. So again my question is, how i can edit DB file, so i can add my own content?

Thank you so much for your time and comment.

**Comment by arashpayan** [comment]
I was under the impression that you wanted to add prayers from the Bahá'í Writings, which would only have to be a one time process (with minor updates in the future due to updated translations).

If you would just like to add your own content to the app, that would be something you'd have to do on your own. To get started down the path, you would have to learn about sqlite, and how to interface with it using whichever programming language in which you are most comfortable working.

The schema of the database file used by the app is specified by the following SQL CREATE statement:
``` sql
CREATE TABLE prayers (id INTEGER PRIMARY KEY,
					category TEXT NOT NULL,
					prayerText TEXT NOT NULL,
					openingWords TEXT NOT NULL,
					citation TEXT NOT NULL,
					author TEXT NOT NULL,
					language TEXT NOT NULL,
					wordCount INTEGER NOT NULL,
					searchText TEXT NOT NULL)
```

A brief explanation of the columns:
* `id`: just a regular table id. nothing special.
* `category`: The category of the prayer. e.g. Healing, Assistance, Children, etc. There are no pre-defined values for this. The app simply determines the unique columns at run time, based on all the `category` values it finds in the database.
* `prayerText`: This is the prayer text marked up with HTML tags used for rendering the prayer in the webview. More info on the tags can be found by watching this video I made several years back, and by examining the code of the app.
* `openingWords`: This is just the opening words of the prayer that is rendered in the list. The app does not guarantee to show all of it. The amount of text rendered is based on the size of the screen of the device running the app.
* `citation`: Some prayers have citation info that needs to be rendered at the bottom of the prayer. If there is none, you can leave this column empty. If it's non-empty, the text here will be rendered at the bottom of the prayer.
* `author`: The name of the author. It gets rendered at the bottom of the prayer.
* `language`: The ISO language code of the prayer. Any value here, needs to also be supported by he app. In the Android app, that means making sure the [`Language`](https://github.com/arashpayan/Prayer-Book-Android/blob/master/app/src/main/java/com/arashpayan/prayerbook/Language.java) enum knows about it. In the iOS app, that means the [`PBLanguage`](https://github.com/arashpayan/prayer-book/blob/master/baha/code/PBLanguage.m) class knows about it.
* `wordCount`: The number of words in the prayer. This is displayed when listing all the prayers in a category.
* `searchText`: This is the same value as the `prayerText` column, but with all the HTML tags removed.

Hopefully that helps. :-)

**Comment by guttevikas7** [comment]
Thank you so much for your time and valuable help...!

**Comment by arashpayan** [comment]
Glad I could help. :smile: 

BTW, I realize that I forgot to include the link to the video explaining HTML tags in my previous message. Here is is: https://ara.sh/PrayerBook/pbdb_overview.mov
