### ISSUE TITLE
Android Malware

### ISSUE THREAD

**Issue by Bastian72** [arashpayan/Prayer-Book-Android#46]
Ikarus Mobile Security reports malware infection with Trojan-Spy.AndroidOS.SMSSpy.

**Comment by arashpayan** [comment]
Did you download the app from somewhere other than Google Play? If so, maybe you downloaded an infected version. However, it's more likely that your phone was infected by some other app on  your phone because the Prayer Book app isn't a very good distribution mechanism due to its limited audience.

If you're unsure of how to remove the infection, I recommend visiting a local cell phone store and asking them for help.

**Comment by Bastian72** [comment]
It was downloaded from the Google Play store. I uninstalled the app
straight away. I just wanted to inform them about the message, as I can't
judge whether this was a false alarm from Ikarus.

Am So., 17. März 2024 um 22:49 Uhr schrieb Arash Payan <
***@***.***>:
